from titik import *
def main():
	bacatulis()
	print('GetAbsis P1				: {:.0f}'.format(getabsis('1')))
	print('Getordinat P1				: {:.0f}'.format(getordinat('1')))
	print('P4 setelah diset (4,4)			: ({},{})'.format(setabsis(4,'4'),setordinat(4,'4')))
	print('P4 setelah diset (-2,2)			: ({},{})'.format(setabsis(-2,'5'),setordinat(2,'5')))
	print('Tulis P5 = P1+P2			: ({})'.format(addp(getabsis('1'),getordinat('1'),getabsis('2'),getordinat('2'))))
	print('Tulis P5 = P1-P2			: ({})'.format(minp(getabsis('1'),getordinat('1'),getabsis('2'),getordinat('2'))))
	print('Tulis P5 = P1.P2			: ({})'.format(muldot(getabsis('1'),getordinat('1'),getabsis('2'),getordinat('2'))))
	print('Equal P1 P2				? {}'.format(isequal(getabsis('1'),getordinat('1'),getabsis('2'),getordinat('2'))))
	print('~Equal P1 P2				? {}'.format(isnotequal(getabsis('1'),getordinat('1'),getabsis('2'),getordinat('2'))))
	print('Less P1 P2				? {}'.format(isless(getabsis('1'),getordinat('1'),getabsis('2'),getordinat('2'))))
	print('Greate P1 P2				? {}'.format(greater(getabsis('1'),getordinat('1'),getabsis('2'),getordinat('2'))))
	print('Origin P1				? {}'.format(isorigin(getabsis('1'),getordinat('1'))))
	print('IsOnSbX P1				? {}'.format(isonsbx(getabsis('1'))))
	print('IsOnSbY P1				? {}'.format(isonsby(getordinat('1'))))
	print('P1 Kuadran ke				: {}'.format(kuadran(getabsis('1'),getordinat('1'))))
	print('P2 Kuadran ke				: {}'.format(kuadran(getabsis('2'),getordinat('2'))))
	print('P3 Kuadran ke				: {}'.format(kuadran(getabsis('3'),getordinat('3'))))
	print('P4 Kuadran ke				: {}'.format(kuadran(getabsis('4'),getordinat('4'))))
	print('Next P1					: ({}, {})'.format(nextx(getabsis('1'),'1'),nexty(getordinat('1'),'1')))
	print('Next P2					: ({}, {})'.format(nextx(getabsis('2'),'2'),nexty(getordinat('2'),'2')))
	print('PlusDelta P3 (2,2)			: ({})'.format(plusdelta(getabsis('3'),getordinat('3'),2,2,'3')))
	print('Mirror P4 SbX				: ({})'.format(mirrorof(getabsis('4'),getordinat('4'),'sbx','4')))
	print('Geser P1 (2,3)				: ({})'.format(geser(getabsis('1'),getordinat('1'),2,3,'1')))
	print('Mirror P2 SbX				: ({})'.format(mirrorof(getabsis('2'),getordinat('2'),'sbx','2')))
	print('Mirror P3 SbY				: ({})'.format(mirrorof(getabsis('3'),getordinat('3'),'sby','3')))
	print('Tulis P1				: ({}, {})'.format(getabsis('1'),getordinat('1')))
	print('Jarak P1 dari (0,0)			: {}'.format(jarakpusat(getabsis('1'),getordinat('1'))))
	print('jarak P1 P2				: {}'.format(jarak2t(getabsis('1'),getordinat('1'),getabsis('2'),getordinat('2'))))
	print('P1 sblm rot 30 CCW			: ({}, {})'.format(getabsis('1'),getordinat('1')))
	print('P1 stlh rot 30 CCW			: ({})'.format(putar(getabsis('1'),getordinat('1'),30)))
	print('P1 stlh rot -30 CCW			: ({})'.format(putar(getabsis('1'),getordinat('1'),-30)))
	print('Koord 2 titik P1 dan P2			: ({})'.format(addp(getabsis('1'),getordinat('1'),getabsis('2'),getordinat('2'))))
if __name__ == '__main__':
	main()