from matematika import *
def main():
	m2=Max2(2,5)
	print(m2)
	m3=Max3(1,2,5)
	print(m3)
	m4=Max4(1,2,5,7)
	print(m4)
	gan1=IsGanjil(23)
	print(gan1)
	gan2=IsGanjil(12)
	print(gan2)
	pri1=IsPrima(2)
	print(pri1)
	pri2=IsPrima(18)
	print(pri2)
	nop=NumOfPrima(25)
	print(nop)
	pan,x,y=Pangkat(2,8)
	print("Hasil dari Pangkat {} dan {} : {}".format(x,y,pan))
	son=SumOfN(3)
	print(son)
if __name__=="__main__":
	main()
